#!/usr/bin/env sh
set -e

yarn lint
yarn typecheck

if git rev-parse --verify origin/main >/dev/null 2>&1; then
  yarn test --passWithNoTests --changedSince=origin/main
else
  yarn test --passWithNoTests
fi